# Generated by Django 6.0.6 on 2026-08-19 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "recommendation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[("STROKE", "Stroke"), ("NON_STROKE", "Non-Stroke")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("content", models.TextField()),
            ],
            options={
                "db_table": "recommendation",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("staff_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("full_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "staff",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "ชาย"), (2, "หญิง")], verbose_name="เพศ"
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="อายุ")),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("Childhood", "เด็ก (0-14 ปี)"),
                            ("Workforce", "วัยทำงาน (15-59 ปี)"),
                            ("Elderly", "ผู้สูงอายุ (60 ปีขึ้นไป)"),
                        ],
                        max_length=20,
                        verbose_name="กลุ่มอายุ",
                    ),
                ),
                (
                    "patient_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "ผู้ป่วยทั่วไป"), (2, "ผู้ป่วยฉุกเฉินวิกฤต")],
                        verbose_name="ประเภทผู้ป่วย",
                    ),
                ),
                (
                    "referral_reason",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "เพื่อการวินิจฉัยและรักษา"),
                            (2, "เพื่อการวินิจฉัย"),
                            (3, "เพื่อการรักษาต่อเนื่อง"),
                            (6, "เกินศักยภาพของสถานพยาบาล"),
                            (7, "ตามความต้องการของผู้ป่วย/ญาติ"),
                            (8, "อื่น ๆ"),
                            (17, "ส่งต่อเพื่อการรักษาเฉพาะทาง"),
                            (99, "ไม่ระบุ"),
                        ],
                        verbose_name="สาเหตุการส่งต่อ",
                    ),
                ),
                (
                    "is_receive",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "ยังไม่ได้ส่งข้อมูลออนไลน์"), (1, "ส่งข้อมูลออนไลน์แล้ว")],
                        default=1,
                        verbose_name="สถานะการส่งข้อมูลออนไลน์",
                    ),
                ),
                (
                    "is_referboard",
                    models.CharField(
                        choices=[("N", "ไม่ใช่"), ("Y", "ใช่")],
                        default="N",
                        max_length=1,
                        verbose_name="แสดงผลใน Refer Board",
                    ),
                ),
                (
                    "f_face",
                    models.CharField(
                        choices=[("N", "ไม่ใช่"), ("Y", "ใช่")],
                        default="N",
                        max_length=1,
                        verbose_name="F: หน้าเบี้ยว",
                    ),
                ),
                (
                    "a_arm",
                    models.CharField(
                        choices=[("N", "ไม่ใช่"), ("Y", "ใช่")],
                        default="N",
                        max_length=1,
                        verbose_name="A: แขนขาอ่อนแรง",
                    ),
                ),
                (
                    "s_speech",
                    models.CharField(
                        choices=[("N", "ไม่ใช่"), ("Y", "ใช่")],
                        default="N",
                        max_length=1,
                        verbose_name="S: พูดไม่ชัด",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("STROKE", "Stroke"), ("NON_STROKE", "Non-Stroke")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients",
                        to="mywebapp.staff",
                    ),
                ),
            ],
            options={
                "db_table": "patient",
                "ordering": ["-assessed_at"],
            },
        ),
    ]
