# Generated by Django 6.0.6 on 2026-09-18 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "hn",
                    models.CharField(
                        help_text="รหัส HN ของโรงพยาบาล รูปแบบ HN ตามด้วยตัวเลข 9 หลัก",
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="รหัส HN ต้องเป็นตัวอักษร HN ตามด้วยตัวเลข 9 หลัก เช่น HN123456789",
                                regex="^HN\\d{9}$",
                            )
                        ],
                        verbose_name="รหัส HN",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="ชื่อ-นามสกุลผู้ป่วย"),
                ),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "ชาย"), (2, "หญิง")],
                        null=True,
                        verbose_name="เพศ",
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="อายุ"
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Early Childhood", "เด็ก 0-5 ปี (Early Childhood)"),
                            (
                                "School-Age Children",
                                "วัยเรียน 5-15 ปี (School-Age Children)",
                            ),
                            ("Workforce", "วัยทำงาน 15-59 ปี (Workforce)"),
                            ("Elderly", "ผู้สูงอายุ 60 ปีขึ้นไป (Elderly)"),
                        ],
                        max_length=30,
                        null=True,
                        verbose_name="กลุ่มอายุ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "patient",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "recommendation_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[("STROKE", "Stroke"), ("NON_STROKE", "Non-Stroke")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("content", models.TextField()),
            ],
            options={
                "db_table": "recommendation",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("staff_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("full_name", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "staff",
            },
        ),
        migrations.CreateModel(
            name="PredictionRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "patient_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "ผู้ป่วยทั่วไป"),
                            (2, "ผู้ป่วยฉุกเฉินวิกฤต"),
                            (3, "ผู้ป่วยเบิกจ่ายตรง"),
                        ],
                        verbose_name="ประเภทผู้ป่วย",
                    ),
                ),
                (
                    "referral_reason",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "เพื่อการวินิจฉัยและรักษา"),
                            (2, "เพื่อการวินิจฉัย"),
                            (3, "เพื่อการรักษาต่อเนื่อง"),
                            (4, "เพื่อการดูแลต่อใกล้บ้าน"),
                            (5, "ตามความต้องการผู้ป่วย"),
                        ],
                        verbose_name="สาเหตุการส่งต่อ",
                    ),
                ),
                (
                    "is_receive",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "ยังไม่ได้ส่งข้อมูลออนไลน์"), (1, "ส่งข้อมูลออนไลน์แล้ว")],
                        default=1,
                        verbose_name="สถานะการส่งข้อมูลออนไลน์",
                    ),
                ),
                (
                    "is_referboard",
                    models.CharField(
                        choices=[("N", "ไม่ใช่"), ("Y", "ใช่")],
                        default="N",
                        max_length=1,
                        verbose_name="แสดงผลใน Refer Board",
                    ),
                ),
                (
                    "f_face",
                    models.CharField(
                        choices=[("N", "ไม่ใช่"), ("Y", "ใช่")],
                        default="N",
                        max_length=1,
                        verbose_name="F: หน้าเบี้ยว",
                    ),
                ),
                (
                    "a_arm",
                    models.CharField(
                        choices=[("N", "ไม่ใช่"), ("Y", "ใช่")],
                        default="N",
                        max_length=1,
                        verbose_name="A: แขนขาอ่อนแรง",
                    ),
                ),
                (
                    "s_speech",
                    models.CharField(
                        choices=[("N", "ไม่ใช่"), ("Y", "ใช่")],
                        default="N",
                        max_length=1,
                        verbose_name="S: พูดไม่ชัด",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("STROKE", "Stroke"), ("NON_STROKE", "Non-Stroke")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="mywebapp.patient",
                        verbose_name="ผู้ป่วย",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="mywebapp.staff",
                    ),
                ),
            ],
            options={
                "db_table": "prediction_record",
                "ordering": ["-assessed_at"],
            },
        ),
    ]
