# Generated by Django 6.0.6 on 2026-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mywebapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="age_group",
            field=models.CharField(
                choices=[
                    ("Early Childhood", "เด็ก 0-5 ปี (Early Childhood)"),
                    ("School-Age Children", "วัยเรียน 5-15 ปี (School-Age Children)"),
                    ("Workforce", "วัยทำงาน 15-59 ปี (Workforce)"),
                    ("Elderly", "ผู้สูงอายุ 60 ปีขึ้นไป (Elderly)"),
                ],
                max_length=30,
                verbose_name="กลุ่มอายุ",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "ผู้ป่วยทั่วไป"), (2, "ผู้ป่วยฉุกเฉินวิกฤต"), (3, "ผู้ป่วยเบิกจ่ายตรง")],
                verbose_name="ประเภทผู้ป่วย",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="referral_reason",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "เพื่อการวินิจฉัยและรักษา"),
                    (2, "เพื่อการวินิจฉัย"),
                    (3, "เพื่อการรักษาต่อเนื่อง"),
                    (4, "เพื่อการดูแลต่อใกล้บ้าน"),
                    (5, "ตามความต้องการผู้ป่วย"),
                ],
                verbose_name="สาเหตุการส่งต่อ",
            ),
        ),
    ]
